// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
namespace com {
namespace net {
namespace proto {
namespace msg {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Message_ParamEntry_DoNotUse;
class Message_ParamEntry_DoNotUseDefaultTypeInternal;
extern Message_ParamEntry_DoNotUseDefaultTypeInternal _Message_ParamEntry_DoNotUse_default_instance_;
class VarMessage;
class VarMessageDefaultTypeInternal;
extern VarMessageDefaultTypeInternal _VarMessage_default_instance_;
class VarMessage_ParamEntry_DoNotUse;
class VarMessage_ParamEntry_DoNotUseDefaultTypeInternal;
extern VarMessage_ParamEntry_DoNotUseDefaultTypeInternal _VarMessage_ParamEntry_DoNotUse_default_instance_;
class Variant;
class VariantDefaultTypeInternal;
extern VariantDefaultTypeInternal _Variant_default_instance_;
}  // namespace msg
}  // namespace proto
}  // namespace net
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::net::proto::msg::Message* Arena::CreateMaybeMessage<::com::net::proto::msg::Message>(Arena*);
template<> ::com::net::proto::msg::Message_ParamEntry_DoNotUse* Arena::CreateMaybeMessage<::com::net::proto::msg::Message_ParamEntry_DoNotUse>(Arena*);
template<> ::com::net::proto::msg::VarMessage* Arena::CreateMaybeMessage<::com::net::proto::msg::VarMessage>(Arena*);
template<> ::com::net::proto::msg::VarMessage_ParamEntry_DoNotUse* Arena::CreateMaybeMessage<::com::net::proto::msg::VarMessage_ParamEntry_DoNotUse>(Arena*);
template<> ::com::net::proto::msg::Variant* Arena::CreateMaybeMessage<::com::net::proto::msg::Variant>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace net {
namespace proto {
namespace msg {

enum MSG : int {
  MSG_UNKNOWN = 0,
  MSG_NOTIFY = 1,
  MSG_REQUEST_DO = 2,
  MSG_REQUEST_QUERY = 3,
  MSG_RESPONSE = 4,
  MSG_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  MSG_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool MSG_IsValid(int value);
constexpr MSG MSG_MIN = MSG_UNKNOWN;
constexpr MSG MSG_MAX = MSG_RESPONSE;
constexpr int MSG_ARRAYSIZE = MSG_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MSG_descriptor();
template<typename T>
inline const std::string& MSG_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MSG>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MSG_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MSG_descriptor(), enum_t_value);
}
inline bool MSG_Parse(
    const std::string& name, MSG* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MSG>(
    MSG_descriptor(), name, value);
}
// ===================================================================

class Variant PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.net.proto.msg.Variant) */ {
 public:
  inline Variant() : Variant(nullptr) {};
  virtual ~Variant();

  Variant(const Variant& from);
  Variant(Variant&& from) noexcept
    : Variant() {
    *this = ::std::move(from);
  }

  inline Variant& operator=(const Variant& from) {
    CopyFrom(from);
    return *this;
  }
  inline Variant& operator=(Variant&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Variant& default_instance();

  enum VariantCase {
    kB = 1,
    kU32 = 2,
    kI32 = 3,
    kU64 = 4,
    kI64 = 5,
    kF32 = 6,
    kF64 = 7,
    kStr = 8,
    kData = 9,
    VARIANT_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Variant* internal_default_instance() {
    return reinterpret_cast<const Variant*>(
               &_Variant_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Variant& a, Variant& b) {
    a.Swap(&b);
  }
  inline void Swap(Variant* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Variant* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Variant* New() const final {
    return CreateMaybeMessage<Variant>(nullptr);
  }

  Variant* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Variant>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Variant& from);
  void MergeFrom(const Variant& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Variant* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.net.proto.msg.Variant";
  }
  protected:
  explicit Variant(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBFieldNumber = 1,
    kU32FieldNumber = 2,
    kI32FieldNumber = 3,
    kU64FieldNumber = 4,
    kI64FieldNumber = 5,
    kF32FieldNumber = 6,
    kF64FieldNumber = 7,
    kStrFieldNumber = 8,
    kDataFieldNumber = 9,
  };
  // bool b = 1;
  private:
  bool _internal_has_b() const;
  public:
  void clear_b();
  bool b() const;
  void set_b(bool value);
  private:
  bool _internal_b() const;
  void _internal_set_b(bool value);
  public:

  // uint32 u32 = 2;
  private:
  bool _internal_has_u32() const;
  public:
  void clear_u32();
  ::PROTOBUF_NAMESPACE_ID::uint32 u32() const;
  void set_u32(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_u32() const;
  void _internal_set_u32(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // sint32 i32 = 3;
  private:
  bool _internal_has_i32() const;
  public:
  void clear_i32();
  ::PROTOBUF_NAMESPACE_ID::int32 i32() const;
  void set_i32(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_i32() const;
  void _internal_set_i32(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // uint64 u64 = 4;
  private:
  bool _internal_has_u64() const;
  public:
  void clear_u64();
  ::PROTOBUF_NAMESPACE_ID::uint64 u64() const;
  void set_u64(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_u64() const;
  void _internal_set_u64(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // sint64 i64 = 5;
  private:
  bool _internal_has_i64() const;
  public:
  void clear_i64();
  ::PROTOBUF_NAMESPACE_ID::int64 i64() const;
  void set_i64(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_i64() const;
  void _internal_set_i64(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // float f32 = 6;
  private:
  bool _internal_has_f32() const;
  public:
  void clear_f32();
  float f32() const;
  void set_f32(float value);
  private:
  float _internal_f32() const;
  void _internal_set_f32(float value);
  public:

  // double f64 = 7;
  private:
  bool _internal_has_f64() const;
  public:
  void clear_f64();
  double f64() const;
  void set_f64(double value);
  private:
  double _internal_f64() const;
  void _internal_set_f64(double value);
  public:

  // string str = 8;
  private:
  bool _internal_has_str() const;
  public:
  void clear_str();
  const std::string& str() const;
  void set_str(const std::string& value);
  void set_str(std::string&& value);
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  std::string* mutable_str();
  std::string* release_str();
  void set_allocated_str(std::string* str);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_str();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_str(
      std::string* str);
  private:
  const std::string& _internal_str() const;
  void _internal_set_str(const std::string& value);
  std::string* _internal_mutable_str();
  public:

  // bytes data = 9;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  void clear_variant();
  VariantCase variant_case() const;
  // @@protoc_insertion_point(class_scope:com.net.proto.msg.Variant)
 private:
  class _Internal;
  void set_has_b();
  void set_has_u32();
  void set_has_i32();
  void set_has_u64();
  void set_has_i64();
  void set_has_f32();
  void set_has_f64();
  void set_has_str();
  void set_has_data();

  inline bool has_variant() const;
  inline void clear_has_variant();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union VariantUnion {
    VariantUnion() {}
    bool b_;
    ::PROTOBUF_NAMESPACE_ID::uint32 u32_;
    ::PROTOBUF_NAMESPACE_ID::int32 i32_;
    ::PROTOBUF_NAMESPACE_ID::uint64 u64_;
    ::PROTOBUF_NAMESPACE_ID::int64 i64_;
    float f32_;
    double f64_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr str_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  } variant_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class VarMessage_ParamEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<VarMessage_ParamEntry_DoNotUse, 
    std::string, ::com::net::proto::msg::Variant,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<VarMessage_ParamEntry_DoNotUse, 
    std::string, ::com::net::proto::msg::Variant,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  VarMessage_ParamEntry_DoNotUse();
  VarMessage_ParamEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const VarMessage_ParamEntry_DoNotUse& other);
  static const VarMessage_ParamEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const VarMessage_ParamEntry_DoNotUse*>(&_VarMessage_ParamEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "com.net.proto.msg.VarMessage.ParamEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class VarMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.net.proto.msg.VarMessage) */ {
 public:
  inline VarMessage() : VarMessage(nullptr) {};
  virtual ~VarMessage();

  VarMessage(const VarMessage& from);
  VarMessage(VarMessage&& from) noexcept
    : VarMessage() {
    *this = ::std::move(from);
  }

  inline VarMessage& operator=(const VarMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline VarMessage& operator=(VarMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VarMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VarMessage* internal_default_instance() {
    return reinterpret_cast<const VarMessage*>(
               &_VarMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(VarMessage& a, VarMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(VarMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VarMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VarMessage* New() const final {
    return CreateMaybeMessage<VarMessage>(nullptr);
  }

  VarMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VarMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VarMessage& from);
  void MergeFrom(const VarMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VarMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.net.proto.msg.VarMessage";
  }
  protected:
  explicit VarMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kParamFieldNumber = 3,
    kDataFieldNumber = 4,
    kTypeFieldNumber = 1,
    kIdFieldNumber = 2,
  };
  // map<string, .com.net.proto.msg.Variant> param = 3;
  int param_size() const;
  private:
  int _internal_param_size() const;
  public:
  void clear_param();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >&
      _internal_param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >*
      _internal_mutable_param();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >&
      param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >*
      mutable_param();

  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 type = 1;
  void clear_type();
  ::PROTOBUF_NAMESPACE_ID::int32 type() const;
  void set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_type() const;
  void _internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 id = 2;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:com.net.proto.msg.VarMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      VarMessage_ParamEntry_DoNotUse,
      std::string, ::com::net::proto::msg::Variant,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > param_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::int32 type_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class Message_ParamEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Message_ParamEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Message_ParamEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  Message_ParamEntry_DoNotUse();
  Message_ParamEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Message_ParamEntry_DoNotUse& other);
  static const Message_ParamEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Message_ParamEntry_DoNotUse*>(&_Message_ParamEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "com.net.proto.msg.Message.ParamEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "com.net.proto.msg.Message.ParamEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[3];
  }

  public:
};

// -------------------------------------------------------------------

class Message PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.net.proto.msg.Message) */ {
 public:
  inline Message() : Message(nullptr) {};
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.net.proto.msg.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kParamFieldNumber = 3,
    kDataFieldNumber = 4,
    kTypeFieldNumber = 1,
    kIdFieldNumber = 2,
  };
  // map<string, string> param = 3;
  int param_size() const;
  private:
  int _internal_param_size() const;
  public:
  void clear_param();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_param();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_param();

  // bytes data = 4;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .com.net.proto.msg.MSG type = 1;
  void clear_type();
  ::com::net::proto::msg::MSG type() const;
  void set_type(::com::net::proto::msg::MSG value);
  private:
  ::com::net::proto::msg::MSG _internal_type() const;
  void _internal_set_type(::com::net::proto::msg::MSG value);
  public:

  // int32 id = 2;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:com.net.proto.msg.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Message_ParamEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      0 > param_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int type_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Variant

// bool b = 1;
inline bool Variant::_internal_has_b() const {
  return variant_case() == kB;
}
inline void Variant::set_has_b() {
  _oneof_case_[0] = kB;
}
inline void Variant::clear_b() {
  if (_internal_has_b()) {
    variant_.b_ = false;
    clear_has_variant();
  }
}
inline bool Variant::_internal_b() const {
  if (_internal_has_b()) {
    return variant_.b_;
  }
  return false;
}
inline void Variant::_internal_set_b(bool value) {
  if (!_internal_has_b()) {
    clear_variant();
    set_has_b();
  }
  variant_.b_ = value;
}
inline bool Variant::b() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.b)
  return _internal_b();
}
inline void Variant::set_b(bool value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.b)
}

// uint32 u32 = 2;
inline bool Variant::_internal_has_u32() const {
  return variant_case() == kU32;
}
inline void Variant::set_has_u32() {
  _oneof_case_[0] = kU32;
}
inline void Variant::clear_u32() {
  if (_internal_has_u32()) {
    variant_.u32_ = 0u;
    clear_has_variant();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Variant::_internal_u32() const {
  if (_internal_has_u32()) {
    return variant_.u32_;
  }
  return 0u;
}
inline void Variant::_internal_set_u32(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  if (!_internal_has_u32()) {
    clear_variant();
    set_has_u32();
  }
  variant_.u32_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Variant::u32() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.u32)
  return _internal_u32();
}
inline void Variant::set_u32(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_u32(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.u32)
}

// sint32 i32 = 3;
inline bool Variant::_internal_has_i32() const {
  return variant_case() == kI32;
}
inline void Variant::set_has_i32() {
  _oneof_case_[0] = kI32;
}
inline void Variant::clear_i32() {
  if (_internal_has_i32()) {
    variant_.i32_ = 0;
    clear_has_variant();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Variant::_internal_i32() const {
  if (_internal_has_i32()) {
    return variant_.i32_;
  }
  return 0;
}
inline void Variant::_internal_set_i32(::PROTOBUF_NAMESPACE_ID::int32 value) {
  if (!_internal_has_i32()) {
    clear_variant();
    set_has_i32();
  }
  variant_.i32_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Variant::i32() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.i32)
  return _internal_i32();
}
inline void Variant::set_i32(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_i32(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.i32)
}

// uint64 u64 = 4;
inline bool Variant::_internal_has_u64() const {
  return variant_case() == kU64;
}
inline void Variant::set_has_u64() {
  _oneof_case_[0] = kU64;
}
inline void Variant::clear_u64() {
  if (_internal_has_u64()) {
    variant_.u64_ = PROTOBUF_ULONGLONG(0);
    clear_has_variant();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Variant::_internal_u64() const {
  if (_internal_has_u64()) {
    return variant_.u64_;
  }
  return PROTOBUF_ULONGLONG(0);
}
inline void Variant::_internal_set_u64(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  if (!_internal_has_u64()) {
    clear_variant();
    set_has_u64();
  }
  variant_.u64_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Variant::u64() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.u64)
  return _internal_u64();
}
inline void Variant::set_u64(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_u64(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.u64)
}

// sint64 i64 = 5;
inline bool Variant::_internal_has_i64() const {
  return variant_case() == kI64;
}
inline void Variant::set_has_i64() {
  _oneof_case_[0] = kI64;
}
inline void Variant::clear_i64() {
  if (_internal_has_i64()) {
    variant_.i64_ = PROTOBUF_LONGLONG(0);
    clear_has_variant();
  }
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Variant::_internal_i64() const {
  if (_internal_has_i64()) {
    return variant_.i64_;
  }
  return PROTOBUF_LONGLONG(0);
}
inline void Variant::_internal_set_i64(::PROTOBUF_NAMESPACE_ID::int64 value) {
  if (!_internal_has_i64()) {
    clear_variant();
    set_has_i64();
  }
  variant_.i64_ = value;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Variant::i64() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.i64)
  return _internal_i64();
}
inline void Variant::set_i64(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_i64(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.i64)
}

// float f32 = 6;
inline bool Variant::_internal_has_f32() const {
  return variant_case() == kF32;
}
inline void Variant::set_has_f32() {
  _oneof_case_[0] = kF32;
}
inline void Variant::clear_f32() {
  if (_internal_has_f32()) {
    variant_.f32_ = 0;
    clear_has_variant();
  }
}
inline float Variant::_internal_f32() const {
  if (_internal_has_f32()) {
    return variant_.f32_;
  }
  return 0;
}
inline void Variant::_internal_set_f32(float value) {
  if (!_internal_has_f32()) {
    clear_variant();
    set_has_f32();
  }
  variant_.f32_ = value;
}
inline float Variant::f32() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.f32)
  return _internal_f32();
}
inline void Variant::set_f32(float value) {
  _internal_set_f32(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.f32)
}

// double f64 = 7;
inline bool Variant::_internal_has_f64() const {
  return variant_case() == kF64;
}
inline void Variant::set_has_f64() {
  _oneof_case_[0] = kF64;
}
inline void Variant::clear_f64() {
  if (_internal_has_f64()) {
    variant_.f64_ = 0;
    clear_has_variant();
  }
}
inline double Variant::_internal_f64() const {
  if (_internal_has_f64()) {
    return variant_.f64_;
  }
  return 0;
}
inline void Variant::_internal_set_f64(double value) {
  if (!_internal_has_f64()) {
    clear_variant();
    set_has_f64();
  }
  variant_.f64_ = value;
}
inline double Variant::f64() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.f64)
  return _internal_f64();
}
inline void Variant::set_f64(double value) {
  _internal_set_f64(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.f64)
}

// string str = 8;
inline bool Variant::_internal_has_str() const {
  return variant_case() == kStr;
}
inline void Variant::set_has_str() {
  _oneof_case_[0] = kStr;
}
inline void Variant::clear_str() {
  if (_internal_has_str()) {
    variant_.str_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
    clear_has_variant();
  }
}
inline const std::string& Variant::str() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.str)
  return _internal_str();
}
inline void Variant::set_str(const std::string& value) {
  _internal_set_str(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.str)
}
inline std::string* Variant::mutable_str() {
  // @@protoc_insertion_point(field_mutable:com.net.proto.msg.Variant.str)
  return _internal_mutable_str();
}
inline const std::string& Variant::_internal_str() const {
  if (_internal_has_str()) {
    return variant_.str_.Get();
  }
  return *&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Variant::_internal_set_str(const std::string& value) {
  if (!_internal_has_str()) {
    clear_variant();
    set_has_str();
    variant_.str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.str_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Variant::set_str(std::string&& value) {
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.str)
  if (!_internal_has_str()) {
    clear_variant();
    set_has_str();
    variant_.str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.str_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:com.net.proto.msg.Variant.str)
}
inline void Variant::set_str(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_str()) {
    clear_variant();
    set_has_str();
    variant_.str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.str_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:com.net.proto.msg.Variant.str)
}
inline void Variant::set_str(const char* value,
                             size_t size) {
  if (!_internal_has_str()) {
    clear_variant();
    set_has_str();
    variant_.str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.str_.Set(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:com.net.proto.msg.Variant.str)
}
inline std::string* Variant::_internal_mutable_str() {
  if (!_internal_has_str()) {
    clear_variant();
    set_has_str();
    variant_.str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return variant_.str_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Variant::release_str() {
  // @@protoc_insertion_point(field_release:com.net.proto.msg.Variant.str)
  if (_internal_has_str()) {
    clear_has_variant();
    return variant_.str_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void Variant::set_allocated_str(std::string* str) {
  if (has_variant()) {
    clear_variant();
  }
  if (str != nullptr) {
    set_has_str();
    variant_.str_.UnsafeSetDefault(str);
  }
  // @@protoc_insertion_point(field_set_allocated:com.net.proto.msg.Variant.str)
}
inline std::string* Variant::unsafe_arena_release_str() {
  // @@protoc_insertion_point(field_unsafe_arena_release:com.net.proto.msg.Variant.str)
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (_internal_has_str()) {
    clear_has_variant();
    return variant_.str_.UnsafeArenaRelease(
        &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void Variant::unsafe_arena_set_allocated_str(std::string* str) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (!_internal_has_str()) {
    variant_.str_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  clear_variant();
  if (str) {
    set_has_str();
    variant_.str_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), str, GetArena());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.net.proto.msg.Variant.str)
}

// bytes data = 9;
inline bool Variant::_internal_has_data() const {
  return variant_case() == kData;
}
inline void Variant::set_has_data() {
  _oneof_case_[0] = kData;
}
inline void Variant::clear_data() {
  if (_internal_has_data()) {
    variant_.data_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
    clear_has_variant();
  }
}
inline const std::string& Variant::data() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Variant.data)
  return _internal_data();
}
inline void Variant::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.data)
}
inline std::string* Variant::mutable_data() {
  // @@protoc_insertion_point(field_mutable:com.net.proto.msg.Variant.data)
  return _internal_mutable_data();
}
inline const std::string& Variant::_internal_data() const {
  if (_internal_has_data()) {
    return variant_.data_.Get();
  }
  return *&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Variant::_internal_set_data(const std::string& value) {
  if (!_internal_has_data()) {
    clear_variant();
    set_has_data();
    variant_.data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Variant::set_data(std::string&& value) {
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Variant.data)
  if (!_internal_has_data()) {
    clear_variant();
    set_has_data();
    variant_.data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:com.net.proto.msg.Variant.data)
}
inline void Variant::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  if (!_internal_has_data()) {
    clear_variant();
    set_has_data();
    variant_.data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:com.net.proto.msg.Variant.data)
}
inline void Variant::set_data(const void* value,
                             size_t size) {
  if (!_internal_has_data()) {
    clear_variant();
    set_has_data();
    variant_.data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  variant_.data_.Set(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size),
      GetArena());
  // @@protoc_insertion_point(field_set_pointer:com.net.proto.msg.Variant.data)
}
inline std::string* Variant::_internal_mutable_data() {
  if (!_internal_has_data()) {
    clear_variant();
    set_has_data();
    variant_.data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  return variant_.data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Variant::release_data() {
  // @@protoc_insertion_point(field_release:com.net.proto.msg.Variant.data)
  if (_internal_has_data()) {
    clear_has_variant();
    return variant_.data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void Variant::set_allocated_data(std::string* data) {
  if (has_variant()) {
    clear_variant();
  }
  if (data != nullptr) {
    set_has_data();
    variant_.data_.UnsafeSetDefault(data);
  }
  // @@protoc_insertion_point(field_set_allocated:com.net.proto.msg.Variant.data)
}
inline std::string* Variant::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:com.net.proto.msg.Variant.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (_internal_has_data()) {
    clear_has_variant();
    return variant_.data_.UnsafeArenaRelease(
        &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  } else {
    return nullptr;
  }
}
inline void Variant::unsafe_arena_set_allocated_data(std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (!_internal_has_data()) {
    variant_.data_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  }
  clear_variant();
  if (data) {
    set_has_data();
    variant_.data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data, GetArena());
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.net.proto.msg.Variant.data)
}

inline bool Variant::has_variant() const {
  return variant_case() != VARIANT_NOT_SET;
}
inline void Variant::clear_has_variant() {
  _oneof_case_[0] = VARIANT_NOT_SET;
}
inline Variant::VariantCase Variant::variant_case() const {
  return Variant::VariantCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// VarMessage

// int32 type = 1;
inline void VarMessage::clear_type() {
  type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VarMessage::_internal_type() const {
  return type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VarMessage::type() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.VarMessage.type)
  return _internal_type();
}
inline void VarMessage::_internal_set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  type_ = value;
}
inline void VarMessage::set_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.VarMessage.type)
}

// int32 id = 2;
inline void VarMessage::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VarMessage::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VarMessage::id() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.VarMessage.id)
  return _internal_id();
}
inline void VarMessage::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void VarMessage::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.VarMessage.id)
}

// map<string, .com.net.proto.msg.Variant> param = 3;
inline int VarMessage::_internal_param_size() const {
  return param_.size();
}
inline int VarMessage::param_size() const {
  return _internal_param_size();
}
inline void VarMessage::clear_param() {
  param_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >&
VarMessage::_internal_param() const {
  return param_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >&
VarMessage::param() const {
  // @@protoc_insertion_point(field_map:com.net.proto.msg.VarMessage.param)
  return _internal_param();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >*
VarMessage::_internal_mutable_param() {
  return param_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::net::proto::msg::Variant >*
VarMessage::mutable_param() {
  // @@protoc_insertion_point(field_mutable_map:com.net.proto.msg.VarMessage.param)
  return _internal_mutable_param();
}

// bytes data = 4;
inline void VarMessage::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& VarMessage::data() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.VarMessage.data)
  return _internal_data();
}
inline void VarMessage::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.VarMessage.data)
}
inline std::string* VarMessage::mutable_data() {
  // @@protoc_insertion_point(field_mutable:com.net.proto.msg.VarMessage.data)
  return _internal_mutable_data();
}
inline const std::string& VarMessage::_internal_data() const {
  return data_.Get();
}
inline void VarMessage::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void VarMessage::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:com.net.proto.msg.VarMessage.data)
}
inline void VarMessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:com.net.proto.msg.VarMessage.data)
}
inline void VarMessage::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:com.net.proto.msg.VarMessage.data)
}
inline std::string* VarMessage::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* VarMessage::release_data() {
  // @@protoc_insertion_point(field_release:com.net.proto.msg.VarMessage.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VarMessage::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:com.net.proto.msg.VarMessage.data)
}
inline std::string* VarMessage::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:com.net.proto.msg.VarMessage.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void VarMessage::unsafe_arena_set_allocated_data(
    std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data != nullptr) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.net.proto.msg.VarMessage.data)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Message

// .com.net.proto.msg.MSG type = 1;
inline void Message::clear_type() {
  type_ = 0;
}
inline ::com::net::proto::msg::MSG Message::_internal_type() const {
  return static_cast< ::com::net::proto::msg::MSG >(type_);
}
inline ::com::net::proto::msg::MSG Message::type() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Message.type)
  return _internal_type();
}
inline void Message::_internal_set_type(::com::net::proto::msg::MSG value) {
  
  type_ = value;
}
inline void Message::set_type(::com::net::proto::msg::MSG value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Message.type)
}

// int32 id = 2;
inline void Message::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Message::id() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Message.id)
  return _internal_id();
}
inline void Message::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void Message::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Message.id)
}

// map<string, string> param = 3;
inline int Message::_internal_param_size() const {
  return param_.size();
}
inline int Message::param_size() const {
  return _internal_param_size();
}
inline void Message::clear_param() {
  param_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
Message::_internal_param() const {
  return param_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
Message::param() const {
  // @@protoc_insertion_point(field_map:com.net.proto.msg.Message.param)
  return _internal_param();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
Message::_internal_mutable_param() {
  return param_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
Message::mutable_param() {
  // @@protoc_insertion_point(field_mutable_map:com.net.proto.msg.Message.param)
  return _internal_mutable_param();
}

// bytes data = 4;
inline void Message::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Message::data() const {
  // @@protoc_insertion_point(field_get:com.net.proto.msg.Message.data)
  return _internal_data();
}
inline void Message::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:com.net.proto.msg.Message.data)
}
inline std::string* Message::mutable_data() {
  // @@protoc_insertion_point(field_mutable:com.net.proto.msg.Message.data)
  return _internal_mutable_data();
}
inline const std::string& Message::_internal_data() const {
  return data_.Get();
}
inline void Message::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Message::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:com.net.proto.msg.Message.data)
}
inline void Message::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:com.net.proto.msg.Message.data)
}
inline void Message::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:com.net.proto.msg.Message.data)
}
inline std::string* Message::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Message::release_data() {
  // @@protoc_insertion_point(field_release:com.net.proto.msg.Message.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Message::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:com.net.proto.msg.Message.data)
}
inline std::string* Message::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:com.net.proto.msg.Message.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Message::unsafe_arena_set_allocated_data(
    std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data != nullptr) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:com.net.proto.msg.Message.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg
}  // namespace proto
}  // namespace net
}  // namespace com

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::com::net::proto::msg::MSG> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::net::proto::msg::MSG>() {
  return ::com::net::proto::msg::MSG_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
