// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zq.proto

#include "zq.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_zq_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_VarMessage_ParamEntry_DoNotUse_zq_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_zq_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Variant_zq_2eproto;
namespace com {
namespace zq {
namespace proto {
namespace msg {
class VariantDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Variant> _instance;
  ::PROTOBUF_NAMESPACE_ID::uint64 u64_;
  ::PROTOBUF_NAMESPACE_ID::int64 i64_;
  double f_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr str_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
} _Variant_default_instance_;
class VarMessage_ParamEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<VarMessage_ParamEntry_DoNotUse> _instance;
} _VarMessage_ParamEntry_DoNotUse_default_instance_;
class VarMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<VarMessage> _instance;
} _VarMessage_default_instance_;
}  // namespace msg
}  // namespace proto
}  // namespace zq
}  // namespace com
static void InitDefaultsscc_info_VarMessage_zq_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::zq::proto::msg::_VarMessage_default_instance_;
    new (ptr) ::com::zq::proto::msg::VarMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::zq::proto::msg::VarMessage::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_VarMessage_zq_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_VarMessage_zq_2eproto}, {
      &scc_info_VarMessage_ParamEntry_DoNotUse_zq_2eproto.base,}};

static void InitDefaultsscc_info_VarMessage_ParamEntry_DoNotUse_zq_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::zq::proto::msg::_VarMessage_ParamEntry_DoNotUse_default_instance_;
    new (ptr) ::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse();
  }
  ::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_VarMessage_ParamEntry_DoNotUse_zq_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_VarMessage_ParamEntry_DoNotUse_zq_2eproto}, {
      &scc_info_Variant_zq_2eproto.base,}};

static void InitDefaultsscc_info_Variant_zq_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::zq::proto::msg::_Variant_default_instance_;
    new (ptr) ::com::zq::proto::msg::Variant();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::zq::proto::msg::Variant::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Variant_zq_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Variant_zq_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_zq_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_zq_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_zq_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_zq_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::Variant, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::Variant, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::com::zq::proto::msg::VariantDefaultTypeInternal, u64_),
  offsetof(::com::zq::proto::msg::VariantDefaultTypeInternal, i64_),
  offsetof(::com::zq::proto::msg::VariantDefaultTypeInternal, f_),
  offsetof(::com::zq::proto::msg::VariantDefaultTypeInternal, str_),
  offsetof(::com::zq::proto::msg::VariantDefaultTypeInternal, data_),
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::Variant, variant_),
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage, type_),
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage, id_),
  PROTOBUF_FIELD_OFFSET(::com::zq::proto::msg::VarMessage, param_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::com::zq::proto::msg::Variant)},
  { 11, 18, sizeof(::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse)},
  { 20, -1, sizeof(::com::zq::proto::msg::VarMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::zq::proto::msg::_Variant_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::zq::proto::msg::_VarMessage_ParamEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::zq::proto::msg::_VarMessage_default_instance_),
};

const char descriptor_table_protodef_zq_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\010zq.proto\022\020com.zq.proto.msg\"^\n\007Variant\022"
  "\r\n\003u64\030\001 \001(\004H\000\022\r\n\003i64\030\002 \001(\022H\000\022\013\n\001f\030\003 \001(\001"
  "H\000\022\r\n\003str\030\004 \001(\tH\000\022\016\n\004data\030\005 \001(\014H\000B\t\n\007var"
  "iant\"\247\001\n\nVarMessage\022\014\n\004type\030\001 \001(\005\022\n\n\002id\030"
  "\002 \001(\005\0226\n\005param\030\003 \003(\0132\'.com.zq.proto.msg."
  "VarMessage.ParamEntry\032G\n\nParamEntry\022\013\n\003k"
  "ey\030\001 \001(\t\022(\n\005value\030\002 \001(\0132\031.com.zq.proto.m"
  "sg.Variant:\0028\001*\253\004\n\022MSG_ID_NOTIFY_TYPE\022\026\n"
  "\022MSG_ID_NOTIFY_NULL\020\000\022\025\n\021MSG_ID_NOTIFY_M"
  "SG\020\001\022\032\n\026MSG_ID_NOTIFY_USER_ADD\020\013\022\035\n\031MSG_"
  "ID_NOTIFY_USER_REMOVE\020\014\022\035\n\031MSG_ID_NOTIFY"
  "_USER_UPDATE\020\r\022\033\n\027MSG_ID_NOTIFY_DB_CREAT"
  "E\020e\022\033\n\027MSG_ID_NOTIFY_DB_DELETE\020f\022\032\n\025MSG_"
  "ID_NOTIFY_TB_INIT\020\311\001\022\032\n\025MSG_ID_NOTIFY_TB"
  "_DROP\020\312\001\022\032\n\025MSG_ID_NOTIFY_TB_META\020\313\001\022\032\n\025"
  "MSG_ID_NOTIFY_TB_ATTR\020\314\001\022\034\n\027MSG_ID_NOTIF"
  "Y_TB_INSERT\020\315\001\022\034\n\027MSG_ID_NOTIFY_TB_APPEN"
  "D\020\316\001\022\034\n\027MSG_ID_NOTIFY_TB_UPDATE\020\317\001\022\034\n\027MS"
  "G_ID_NOTIFY_TB_REMOVE\020\320\001\022\"\n\035MSG_ID_NOTIF"
  "Y_TB_UPDATE_FIELD\020\321\001\022\"\n\035MSG_ID_NOTIFY_TD"
  "_ORDER_INSERT\020\255\002\022\"\n\035MSG_ID_NOTIFY_TD_ORD"
  "ER_CANCEL\020\256\002*\367\004\n\026MSG_ID_REQUEST_DO_TYPE\022"
  "\032\n\026MSG_ID_REQUEST_DO_NULL\020\000\022\031\n\025MSG_ID_RE"
  "QUEST_DO_MSG\020\001\022\036\n\032MSG_ID_REQUEST_DO_USER"
  "_ADD\020\013\022!\n\035MSG_ID_REQUEST_DO_USER_REMOVE\020"
  "\014\022!\n\035MSG_ID_REQUEST_DO_USER_UPDATE\020\r\022\037\n\033"
  "MSG_ID_REQUEST_DO_DB_CREATE\020e\022\037\n\033MSG_ID_"
  "REQUEST_DO_DB_DELETE\020f\022\036\n\031MSG_ID_REQUEST"
  "_DO_TB_INIT\020\311\001\022\036\n\031MSG_ID_REQUEST_DO_TB_D"
  "ROP\020\312\001\022\036\n\031MSG_ID_REQUEST_DO_TB_META\020\313\001\022\036"
  "\n\031MSG_ID_REQUEST_DO_TB_ATTR\020\314\001\022 \n\033MSG_ID"
  "_REQUEST_DO_TB_INSERT\020\315\001\022 \n\033MSG_ID_REQUE"
  "ST_DO_TB_APPEND\020\316\001\022 \n\033MSG_ID_REQUEST_DO_"
  "TB_UPDATE\020\317\001\022 \n\033MSG_ID_REQUEST_DO_TB_REM"
  "OVE\020\320\001\022&\n!MSG_ID_REQUEST_DO_TB_UPDATE_FI"
  "ELD\020\321\001\022&\n!MSG_ID_REQUEST_DO_TD_ORDER_INS"
  "ERT\020\255\002\022&\n!MSG_ID_REQUEST_DO_TD_ORDER_CAN"
  "CEL\020\256\002*\224\001\n\031MSG_ID_REQUEST_QUERY_TYPE\022\035\n\031"
  "MSG_ID_REQUEST_QUERY_NULL\020\000\022\035\n\031MSG_ID_RE"
  "QUEST_QUERY_USER\020\n\022\033\n\027MSG_ID_REQUEST_QUE"
  "RY_DB\020d\022\034\n\027MSG_ID_REQUEST_QUERY_TB\020\310\001b\006p"
  "roto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_zq_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_zq_2eproto_sccs[3] = {
  &scc_info_VarMessage_zq_2eproto.base,
  &scc_info_VarMessage_ParamEntry_DoNotUse_zq_2eproto.base,
  &scc_info_Variant_zq_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_zq_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_zq_2eproto = {
  false, false, descriptor_table_protodef_zq_2eproto, "zq.proto", 1645,
  &descriptor_table_zq_2eproto_once, descriptor_table_zq_2eproto_sccs, descriptor_table_zq_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_zq_2eproto::offsets,
  file_level_metadata_zq_2eproto, 3, file_level_enum_descriptors_zq_2eproto, file_level_service_descriptors_zq_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_zq_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_zq_2eproto)), true);
namespace com {
namespace zq {
namespace proto {
namespace msg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MSG_ID_NOTIFY_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_zq_2eproto);
  return file_level_enum_descriptors_zq_2eproto[0];
}
bool MSG_ID_NOTIFY_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 11:
    case 12:
    case 13:
    case 101:
    case 102:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 206:
    case 207:
    case 208:
    case 209:
    case 301:
    case 302:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MSG_ID_REQUEST_DO_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_zq_2eproto);
  return file_level_enum_descriptors_zq_2eproto[1];
}
bool MSG_ID_REQUEST_DO_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 11:
    case 12:
    case 13:
    case 101:
    case 102:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
    case 206:
    case 207:
    case 208:
    case 209:
    case 301:
    case 302:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MSG_ID_REQUEST_QUERY_TYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_zq_2eproto);
  return file_level_enum_descriptors_zq_2eproto[2];
}
bool MSG_ID_REQUEST_QUERY_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 10:
    case 100:
    case 200:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Variant::InitAsDefaultInstance() {
  ::com::zq::proto::msg::_Variant_default_instance_.u64_ = PROTOBUF_ULONGLONG(0);
  ::com::zq::proto::msg::_Variant_default_instance_.i64_ = PROTOBUF_LONGLONG(0);
  ::com::zq::proto::msg::_Variant_default_instance_.f_ = 0;
  ::com::zq::proto::msg::_Variant_default_instance_.str_.UnsafeSetDefault(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::com::zq::proto::msg::_Variant_default_instance_.data_.UnsafeSetDefault(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
class Variant::_Internal {
 public:
};

Variant::Variant(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.zq.proto.msg.Variant)
}
Variant::Variant(const Variant& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_variant();
  switch (from.variant_case()) {
    case kU64: {
      _internal_set_u64(from._internal_u64());
      break;
    }
    case kI64: {
      _internal_set_i64(from._internal_i64());
      break;
    }
    case kF: {
      _internal_set_f(from._internal_f());
      break;
    }
    case kStr: {
      _internal_set_str(from._internal_str());
      break;
    }
    case kData: {
      _internal_set_data(from._internal_data());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:com.zq.proto.msg.Variant)
}

void Variant::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Variant_zq_2eproto.base);
  clear_has_variant();
}

Variant::~Variant() {
  // @@protoc_insertion_point(destructor:com.zq.proto.msg.Variant)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Variant::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (has_variant()) {
    clear_variant();
  }
}

void Variant::ArenaDtor(void* object) {
  Variant* _this = reinterpret_cast< Variant* >(object);
  (void)_this;
}
void Variant::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Variant::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Variant& Variant::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Variant_zq_2eproto.base);
  return *internal_default_instance();
}


void Variant::clear_variant() {
// @@protoc_insertion_point(one_of_clear_start:com.zq.proto.msg.Variant)
  switch (variant_case()) {
    case kU64: {
      // No need to clear
      break;
    }
    case kI64: {
      // No need to clear
      break;
    }
    case kF: {
      // No need to clear
      break;
    }
    case kStr: {
      variant_.str_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
      break;
    }
    case kData: {
      variant_.data_.Destroy(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = VARIANT_NOT_SET;
}


void Variant::Clear() {
// @@protoc_insertion_point(message_clear_start:com.zq.proto.msg.Variant)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_variant();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Variant::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 u64 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _internal_set_u64(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // sint64 i64 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _internal_set_i64(::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double f = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          _internal_set_f(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string str = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_str();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "com.zq.proto.msg.Variant.str"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_data();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Variant::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.zq.proto.msg.Variant)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 u64 = 1;
  if (_internal_has_u64()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_u64(), target);
  }

  // sint64 i64 = 2;
  if (_internal_has_i64()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt64ToArray(2, this->_internal_i64(), target);
  }

  // double f = 3;
  if (_internal_has_f()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_f(), target);
  }

  // string str = 4;
  if (_internal_has_str()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_str().data(), static_cast<int>(this->_internal_str().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.zq.proto.msg.Variant.str");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_str(), target);
  }

  // bytes data = 5;
  if (_internal_has_data()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.zq.proto.msg.Variant)
  return target;
}

size_t Variant::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.zq.proto.msg.Variant)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (variant_case()) {
    // uint64 u64 = 1;
    case kU64: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
          this->_internal_u64());
      break;
    }
    // sint64 i64 = 2;
    case kI64: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt64Size(
          this->_internal_i64());
      break;
    }
    // double f = 3;
    case kF: {
      total_size += 1 + 8;
      break;
    }
    // string str = 4;
    case kStr: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_str());
      break;
    }
    // bytes data = 5;
    case kData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_data());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Variant::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.zq.proto.msg.Variant)
  GOOGLE_DCHECK_NE(&from, this);
  const Variant* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Variant>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.zq.proto.msg.Variant)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.zq.proto.msg.Variant)
    MergeFrom(*source);
  }
}

void Variant::MergeFrom(const Variant& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.zq.proto.msg.Variant)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.variant_case()) {
    case kU64: {
      _internal_set_u64(from._internal_u64());
      break;
    }
    case kI64: {
      _internal_set_i64(from._internal_i64());
      break;
    }
    case kF: {
      _internal_set_f(from._internal_f());
      break;
    }
    case kStr: {
      _internal_set_str(from._internal_str());
      break;
    }
    case kData: {
      _internal_set_data(from._internal_data());
      break;
    }
    case VARIANT_NOT_SET: {
      break;
    }
  }
}

void Variant::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.zq.proto.msg.Variant)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Variant::CopyFrom(const Variant& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.zq.proto.msg.Variant)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Variant::IsInitialized() const {
  return true;
}

void Variant::InternalSwap(Variant* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(variant_, other->variant_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Variant::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

VarMessage_ParamEntry_DoNotUse::VarMessage_ParamEntry_DoNotUse() {}
VarMessage_ParamEntry_DoNotUse::VarMessage_ParamEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void VarMessage_ParamEntry_DoNotUse::MergeFrom(const VarMessage_ParamEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata VarMessage_ParamEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void VarMessage_ParamEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void VarMessage::InitAsDefaultInstance() {
}
class VarMessage::_Internal {
 public:
};

VarMessage::VarMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  param_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.zq.proto.msg.VarMessage)
}
VarMessage::VarMessage(const VarMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  param_.MergeFrom(from.param_);
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&type_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:com.zq.proto.msg.VarMessage)
}

void VarMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_VarMessage_zq_2eproto.base);
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&type_)) + sizeof(id_));
}

VarMessage::~VarMessage() {
  // @@protoc_insertion_point(destructor:com.zq.proto.msg.VarMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void VarMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void VarMessage::ArenaDtor(void* object) {
  VarMessage* _this = reinterpret_cast< VarMessage* >(object);
  (void)_this;
}
void VarMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void VarMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const VarMessage& VarMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_VarMessage_zq_2eproto.base);
  return *internal_default_instance();
}


void VarMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:com.zq.proto.msg.VarMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  param_.Clear();
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&type_)) + sizeof(id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VarMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<string, .com.zq.proto.msg.Variant> param = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&param_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* VarMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.zq.proto.msg.VarMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_type(), target);
  }

  // int32 id = 2;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_id(), target);
  }

  // map<string, .com.zq.proto.msg.Variant> param = 3;
  if (!this->_internal_param().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::zq::proto::msg::Variant >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "com.zq.proto.msg.VarMessage.ParamEntry.key");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_param().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_param().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::zq::proto::msg::Variant >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::zq::proto::msg::Variant >::const_iterator
          it = this->_internal_param().begin();
          it != this->_internal_param().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = VarMessage_ParamEntry_DoNotUse::Funcs::InternalSerialize(3, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::zq::proto::msg::Variant >::const_iterator
          it = this->_internal_param().begin();
          it != this->_internal_param().end(); ++it) {
        target = VarMessage_ParamEntry_DoNotUse::Funcs::InternalSerialize(3, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.zq.proto.msg.VarMessage)
  return target;
}

size_t VarMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.zq.proto.msg.VarMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .com.zq.proto.msg.Variant> param = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_param_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::com::zq::proto::msg::Variant >::const_iterator
      it = this->_internal_param().begin();
      it != this->_internal_param().end(); ++it) {
    total_size += VarMessage_ParamEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // int32 type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_type());
  }

  // int32 id = 2;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VarMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.zq.proto.msg.VarMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const VarMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<VarMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.zq.proto.msg.VarMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.zq.proto.msg.VarMessage)
    MergeFrom(*source);
  }
}

void VarMessage::MergeFrom(const VarMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.zq.proto.msg.VarMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  param_.MergeFrom(from.param_);
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
}

void VarMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.zq.proto.msg.VarMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VarMessage::CopyFrom(const VarMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.zq.proto.msg.VarMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VarMessage::IsInitialized() const {
  return true;
}

void VarMessage::InternalSwap(VarMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  param_.Swap(&other->param_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VarMessage, id_)
      + sizeof(VarMessage::id_)
      - PROTOBUF_FIELD_OFFSET(VarMessage, type_)>(
          reinterpret_cast<char*>(&type_),
          reinterpret_cast<char*>(&other->type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VarMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
}  // namespace proto
}  // namespace zq
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::zq::proto::msg::Variant* Arena::CreateMaybeMessage< ::com::zq::proto::msg::Variant >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::zq::proto::msg::Variant >(arena);
}
template<> PROTOBUF_NOINLINE ::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse* Arena::CreateMaybeMessage< ::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::zq::proto::msg::VarMessage_ParamEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::com::zq::proto::msg::VarMessage* Arena::CreateMaybeMessage< ::com::zq::proto::msg::VarMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::zq::proto::msg::VarMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
